### ISSUE TITLE
Crear página web 

### ISSUE THREAD

**Issue by yasminalamo** [hrg1002/Software#14]

**Comment by hrg1002** [comment]
[tips]
(https://www.hostinger.es/tutoriales/5-cosas-que-deberias-saber-antes-de-crear-un-sitio-web?ppc_campaign=google_search_generic_hosting_all&bidkw=defaultkeyword&lo=1005450&gclid=Cj0KCQiAx6ugBhCcARIsAGNmMbhEFCiFYDMuHDW69iFUWb33LlzkC0SUauxS1oadMjLpPilF3M5wDlAaAsa8EALw_wcB)

**Comment by yasminalamo** [comment]
Como crear la [estructura](https://www.lucushost.com/blog/partes-de-una-pagina-web-estructura-y-contenido/) de la pagina.

**Comment by yasminalamo** [comment]
[Peligros](https://andaluciavuela.es/noticias/los-cinco-riesgos-mas-comunes-que-te-puedes-encontrar-en-internet/) de las páginas web.

**Comment by yasminalamo** [comment]
[Asegurar](https://blog.interdominios.com/como-hacer-una-pagina-web-segura/) la página web.
